# Generated by Django 6.0.2 on 2026-03-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_patient'),
        ('patients', '0002_remove_patient_assigned_clinician_and_more'),
        ('telemetry', '0002_alter_sensorframe_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
