# Generated by Django 6.0.2 on 2026-03-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_delete_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='contact_area_threshold',
            field=models.FloatField(default=50.0, help_text='Percentage of contact area that is concerning for this patient'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='duration_threshold',
            field=models.IntegerField(default=300, help_text="Seconds of sustained pressure above threshold before it's risky"),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='pressure_threshold',
            field=models.IntegerField(default=2000, help_text='Pressure value (1-4095) above which the patient considers painful'),
        ),
    ]
