# Generated by Django 6.0.2 on 2026-03-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtable',
            old_name='name',
            new_name='email',
        ),
        migrations.AddField(
            model_name='testtable',
            name='passwords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
