# Generated by Django 6.0.2 on 2026-03-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_testtable_email_testtable_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtable',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
