# Generated by Django 6.0.2 on 2026-02-17 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_type", models.CharField(max_length=50)),
                ("severity", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="patients.patient",
                    ),
                ),
                (
                    "sensor_frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="telemetry.sensorframe",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["patient", "-created_at"],
                        name="alerts_aler_patient_6978ea_idx",
                    ),
                    models.Index(
                        fields=["severity"], name="alerts_aler_severit_202179_idx"
                    ),
                ],
            },
        ),
    ]
