# Generated by Django 6.0.2 on 2026-03-03 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('patients', '0002_remove_patient_assigned_clinician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.patientprofile'),
        ),
    ]
