# Generated by Django 6.0.2 on 2026-03-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_patient'),
        ('patients', '0003_delete_patient'),
        ('telemetry', '0002_alter_sensorframe_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=20),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='alerts_aler_status_2a92cb_idx'),
        ),
    ]
