# Generated by Django 6.0.2 on 2026-03-17 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientprofile_contact_area_threshold_and_more'),
        ('telemetry', '0002_alter_sensorframe_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorframe',
            name='frame_number',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PressureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField()),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('total_frames', models.IntegerField(default=0)),
                ('filename', models.CharField(max_length=255)),
                ('avg_peak_pressure', models.FloatField(blank=True, null=True)),
                ('avg_contact_area', models.FloatField(blank=True, null=True)),
                ('avg_pressure', models.FloatField(blank=True, null=True)),
                ('avg_risk_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressure_sessions', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='FrameMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('peak_pressure_index', models.FloatField()),
                ('contact_area_percent', models.FloatField()),
                ('average_pressure', models.FloatField()),
                ('risk_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor_frame', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='telemetry.sensorframe')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_metrics', to='telemetry.pressuresession')),
            ],
            options={
                'ordering': ['frame_number'],
            },
        ),
        migrations.AddField(
            model_name='sensorframe',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='telemetry.pressuresession'),
        ),
        migrations.AddIndex(
            model_name='sensorframe',
            index=models.Index(fields=['session', 'frame_number'], name='telemetry_s_session_5d9157_idx'),
        ),
        migrations.AddIndex(
            model_name='pressuresession',
            index=models.Index(fields=['patient', '-session_date'], name='telemetry_p_patient_74db12_idx'),
        ),
        migrations.AddIndex(
            model_name='framemetrics',
            index=models.Index(fields=['session', 'frame_number'], name='telemetry_f_session_4ae47b_idx'),
        ),
        migrations.AddIndex(
            model_name='framemetrics',
            index=models.Index(fields=['session', 'timestamp'], name='telemetry_f_session_75beb5_idx'),
        ),
    ]
