# Generated by Django 6.0.2 on 2026-03-18 01:55

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_index', models.PositiveIntegerField()),
                ('pixels', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=1024)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='datainput.uploadsession')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_pressure_index', models.FloatField(default=0)),
                ('contact_area_percent', models.FloatField(default=0)),
                ('has_high_pressure', models.BooleanField(default=False)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('analysed_at', models.DateTimeField(auto_now_add=True)),
                ('frame', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='datainput.imageframe')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='datainput.uploadsession')),
            ],
        ),
    ]
